#--------------- UNDER DEV

name: Python CI

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner, if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Choose your desired Python version

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install ruff  # Install the 'ruff' library

    - name: Run tests
      run: |
        # Replace 'your_test_command' with the actual test command for your project
        ruff your_test_command

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: path/to/your/test/results  # Replace with the path to your test result files
